### ISSUE TITLE
Util リストコンポーネント&Vuexの実装

### ISSUE THREAD

**Issue by striderkein** [WakatsukiYuto/prototypetest#10]
一覧系画面がほとんどなので、「アブストラクトな Util リストコンポーネント（仮）」を作れば楽ができそう。

**Comment by striderkein** [comment]
というか、
これを作るか
Vuex を使うか
の二択でしょうか…？

**Comment by striderkein** [comment]
[この記事](https://qiita.com/d-dai/items/7df318b9369be3d58a58) を読んで Vuex をようやく理解しつつあります。
親コンポーネントから mutations を実行
→ 子コンポーネントたる「アブストラクトなUtilリストコンポーネント」は getters から値を取得
ていう流れが理想、でしょうか？

**Comment by WakatsukiYuto** [comment]
https://qiita.com/nmgw1119/items/27ed23e433ec54a9c950
参考にしてください。
gettersの使い方がよくわかると思う。

**Comment by striderkein** [comment]
「親コンポーネントから子コンポーネントにデータを渡して import した List コンポーネントで描画する」ができたっぽい〜です（画像の赤枠内）
![image](https://user-images.githubusercontent.com/1096708/107115885-f04d5780-68b2-11eb-8ac7-dd0d20c5fe4f.png)

**Comment by striderkein** [comment]
テーブルについては
[vue-good-table](https://github.com/xaksis/vue-good-table) というライブラリがあり、
- ソート
- ページネート
e.t.c. の機能が使えるようになるっぽいです。
[解説ページ](https://www.kabanoki.net/3230/)

**Comment by striderkein** [comment]
vue-good-table の使い方を [wiki](https://github.com/WakatsukiYuto/prototypetest/wiki/vue-good-table%E3%81%AE%E4%BD%BF%E3%81%84%E6%96%B9) にまとめておきました。

**Comment by striderkein** [comment]
> 一覧系画面がほとんどなので、「アブストラクトな Util リストコンポーネント（仮）」を作れば楽ができそう。

→ vue-good-table を使えば要件が満たせそうなので当該アブストラクトコンポーネントをあえて作る必要は無さそう、という結論に達しました。

**Comment by striderkein** [comment]
上記 PR が  `main` にマージされれば本イシューは自動的にクローズされる（はず）のだが、整理したいので手動でクローズしときます。
